# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './uis/loginwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 50, 440, 382))
        self.layoutWidget.setObjectName("layoutWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.mainLayout.setContentsMargins(100, 100, 100, 100)
        self.mainLayout.setObjectName("mainLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.mainLayout.addLayout(self.horizontalLayout_2)
        self.le_login = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_login.setMinimumSize(QtCore.QSize(240, 40))
        self.le_login.setMaxLength(32)
        self.le_login.setObjectName("le_login")
        self.mainLayout.addWidget(self.le_login)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.le_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_password.setMinimumSize(QtCore.QSize(240, 40))
        self.le_password.setText("")
        self.le_password.setMaxLength(60)
        self.le_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_password.setObjectName("le_password")
        self.mainLayout.addWidget(self.le_password)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_login = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_login.setObjectName("pb_login")
        self.horizontalLayout_3.addWidget(self.pb_login)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pb_register = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_register.setObjectName("pb_register")
        self.horizontalLayout_3.addWidget(self.pb_register)
        self.mainLayout.addLayout(self.horizontalLayout_3)
        self.mainLayout.setStretch(0, 1)
        self.mainLayout.setStretch(1, 2)
        self.mainLayout.setStretch(2, 1)
        self.mainLayout.setStretch(3, 2)
        self.mainLayout.setStretch(4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Логин:"))
        self.label_2.setText(_translate("MainWindow", "Пароль:"))
        self.pb_login.setText(_translate("MainWindow", "Войти"))
        self.pb_register.setText(_translate("MainWindow", "Регистрация"))
